-- AUTO-GENERATED by `mcpp emit xpkg`-equivalent (manual seed).
-- Source: https://github.com/mcpp-community/templates @ v0.0.1
-- Form A descriptor: the source repo has its own mcpp.toml, so no
-- `mcpp = {}` workaround segment is needed.
package = {
    spec        = "1",
    name        = "mcpplibs.templates",
    description = "Minimal C++23 modular hello library",
    licenses    = {"Apache-2.0"},
    repo        = "https://github.com/mcpp-community/templates",
    type        = "package",

    xpm = {
        linux = {
            ["0.0.1"] = {
                url    = "https://github.com/mcpp-community/templates/archive/refs/tags/v0.0.1.tar.gz",
                sha256 = "348640a5b8fb09c6392e5487234f426f0d1dd6b1ed46e6644cdec3c9d65e7fd3",
            },
        },
        macosx = {
            ["0.0.1"] = {
                url    = "https://github.com/mcpp-community/templates/archive/refs/tags/v0.0.1.tar.gz",
                sha256 = "348640a5b8fb09c6392e5487234f426f0d1dd6b1ed46e6644cdec3c9d65e7fd3",
            },
        },
        windows = {
            ["0.0.1"] = {
                url    = "https://github.com/mcpp-community/templates/archive/refs/tags/v0.0.1.tar.gz",
                sha256 = "348640a5b8fb09c6392e5487234f426f0d1dd6b1ed46e6644cdec3c9d65e7fd3",
            },
        },
    },
}
